### Connexion
POST http://localhost:8000/api/login_check
content-type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Deconnexion
POST http://localhost:8000/logout
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk4ODYwNDcsImV4cCI6MTY5OTg4OTY0Nywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.fQtmL86OgQC4RbykasaBehw6iPNOPiwlv2DCn8S2EhkDh2K_wUlOMCK2sKd_MyPlueGEhGIvWrSK1Ym94ioG9LTxh3MCh31zetiVu2_p0PZBHiEhbzTZqMwW7tH_As8aFiIm6lDc9l3a5OvrTZBwvqZbjzg0bHuKL5BSe1VdyInjiz12lELV5Zk7Em2G5ZKURDaRjiGq311ZX3BFD8hFmcxoP029RjESjZV761yOskp486NL3JfOAPcse_cmIQH0rQGhg1e_uvP7wf2asaH3WyxgoKvOdR5qR0slA3O2TB3PNUMDkCiZmlGcW7JuPO7ZUZuKJajhSU2bdQ4Q_fRTfQDY2_VpkkayyYkwdfRlWStIWkD-L38gsNKInIFOwBa1m5BsISJSmmnYHh5Z8QNLEKSEbnLL-hA77__RQpGYlBch9S8jzdBsstl0oNld5LOhrXNo6Zknb8BAupd9yb1UWfzQu2iRg2PjTyKmx2s0EAzulcRS11xvuukzcFFCEXkrCmii1x3rGAomYCVAOZsYGyh_xFe3dXx8bRsAjPw58UbwBjymOIGmV5c5OhursK6w5NfHp1S37zRu-4lfdewaUwwaHHuR1wjERECm4SftslD3fZK_22jRtyzd36yYG3uMFFiFTxYhMOHf_W_8dU0rIx6YpZrAK6wz-yYBOhSKMfo

### Liste des favoris
GET http://localhost:8000/api/favorite/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk4ODYyNjEsImV4cCI6MTY5OTg4OTg2MSwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.s-dnbWGWcMVsQjfq-zGp5-6RRO4S-vY0487upR46ALRDxPKN1qp_7o3fMMGuXQbDjZjuYBPLFFoQfIyAZJpCI5CRdHrUm7cyJ9pOLv1vzBZFZenYtq5Le2ZaB5eCFGeAEdtSUmLYrOUT97wLpyO019Z2Z5u74tq2zJh86OZ_U-XqgyFkES82yVrXmNexWR478pv45NzULLYH7rNWGgxFKCYWH1cBGHCYkOgvksedc0cVJs6wb2SQ5VJEUjlH0PcOWBV-nev38I2FY5fDJFx4XFFmZWMLHnY6zxLT7Uy1jBiyY2rm9PnfU3BeLkux4Rwshbpp3C3u152a-8G3aUescl0VUsVawNHb-jWGKokegWZBhs5xXo-4H-E_gaNXY34XQxzajPXgLOklh1OrTcOMFzOfwOS-RQtmIuNUHzGNoXgH_2MUjGuO6_gJiByvu8U_s3ji4e0YZIqr6jZsb5-_AUwipzPyA-sYLYaTl6ZnxwSAp7DiBLmHkAdGGTER4mUSBmtjo0cuvcBaEAHRrp3QGzrqlQ60BVHIEVplGFt75LdYkUHPCy8gCgiytVYOSWpXYy-Z15xNelWpeNBWrIeAFTrApdLndiUi3yyHOMUv0dHnUPmclnHTwBA2Vk08RGAvZX4mn9ZIUXg3NZKfQXZAy8ZdBeTHCtCaZ6GhPc3OTZU

### Suppression d'un favoris
DELETE http://localhost:8000/api/favorite/delete/134
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk4ODYwNDcsImV4cCI6MTY5OTg4OTY0Nywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.fQtmL86OgQC4RbykasaBehw6iPNOPiwlv2DCn8S2EhkDh2K_wUlOMCK2sKd_MyPlueGEhGIvWrSK1Ym94ioG9LTxh3MCh31zetiVu2_p0PZBHiEhbzTZqMwW7tH_As8aFiIm6lDc9l3a5OvrTZBwvqZbjzg0bHuKL5BSe1VdyInjiz12lELV5Zk7Em2G5ZKURDaRjiGq311ZX3BFD8hFmcxoP029RjESjZV761yOskp486NL3JfOAPcse_cmIQH0rQGhg1e_uvP7wf2asaH3WyxgoKvOdR5qR0slA3O2TB3PNUMDkCiZmlGcW7JuPO7ZUZuKJajhSU2bdQ4Q_fRTfQDY2_VpkkayyYkwdfRlWStIWkD-L38gsNKInIFOwBa1m5BsISJSmmnYHh5Z8QNLEKSEbnLL-hA77__RQpGYlBch9S8jzdBsstl0oNld5LOhrXNo6Zknb8BAupd9yb1UWfzQu2iRg2PjTyKmx2s0EAzulcRS11xvuukzcFFCEXkrCmii1x3rGAomYCVAOZsYGyh_xFe3dXx8bRsAjPw58UbwBjymOIGmV5c5OhursK6w5NfHp1S37zRu-4lfdewaUwwaHHuR1wjERECm4SftslD3fZK_22jRtyzd36yYG3uMFFiFTxYhMOHf_W_8dU0rIx6YpZrAK6wz-yYBOhSKMfo

### Ajout d'un favoris
POST http://localhost:8000/api/favorite/add/138
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2OTk4ODYwNDcsImV4cCI6MTY5OTg4OTY0Nywicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.fQtmL86OgQC4RbykasaBehw6iPNOPiwlv2DCn8S2EhkDh2K_wUlOMCK2sKd_MyPlueGEhGIvWrSK1Ym94ioG9LTxh3MCh31zetiVu2_p0PZBHiEhbzTZqMwW7tH_As8aFiIm6lDc9l3a5OvrTZBwvqZbjzg0bHuKL5BSe1VdyInjiz12lELV5Zk7Em2G5ZKURDaRjiGq311ZX3BFD8hFmcxoP029RjESjZV761yOskp486NL3JfOAPcse_cmIQH0rQGhg1e_uvP7wf2asaH3WyxgoKvOdR5qR0slA3O2TB3PNUMDkCiZmlGcW7JuPO7ZUZuKJajhSU2bdQ4Q_fRTfQDY2_VpkkayyYkwdfRlWStIWkD-L38gsNKInIFOwBa1m5BsISJSmmnYHh5Z8QNLEKSEbnLL-hA77__RQpGYlBch9S8jzdBsstl0oNld5LOhrXNo6Zknb8BAupd9yb1UWfzQu2iRg2PjTyKmx2s0EAzulcRS11xvuukzcFFCEXkrCmii1x3rGAomYCVAOZsYGyh_xFe3dXx8bRsAjPw58UbwBjymOIGmV5c5OhursK6w5NfHp1S37zRu-4lfdewaUwwaHHuR1wjERECm4SftslD3fZK_22jRtyzd36yYG3uMFFiFTxYhMOHf_W_8dU0rIx6YpZrAK6wz-yYBOhSKMfo