### Liste des member
GET http://localhost:8000/api/member

### Détail d'un member
GET http://localhost:8000/api/member/9
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MDAxMDAwOTQsImV4cCI6MTcwMDEwMzY5NCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluIn0.F6byZ0dbPniQ4xHbUa4Ir-FzHjs85t724GOEpmrXOdTdeA5hrecisWRcjFGFy6PKcHZT6e-3ty8ctkAYOeiWqRcZM-HaWICKxbWuJS4-adbZO47Q3Zxo49kxgb_CFzj6nJIakcuzhMVU18ZWNuc-jNOxnpIp8Jx_GP4LhWl9rtm0hSKorpfXkBMMINzqryQVSuF8Zhkvj2CqR9Gkn0yfvJo1Hbdm9ewGs-uXIq1iT9m8Y2V3sedqqu7lQyzVHEkL1LFlweP7ltg5ND1_0OJywCDro8iE4DQtpvfwShVA08-VaLtrEjU04P3goeWwVomPd4GuLEqZZK5rmIiKZyQ_6ps9jZwEWc0mPFR-Rw-slIFtRvB_9d4mxDVh7Q5roq9InLBTwhsftdlF9oRQbl4eXoo_zNo5jBB-924OPgFOCDNpvTXPkOb0ea1TD5GnhoSbEXcXBNlzturHlkOC-tNnCxkly26g-eN2gYlxOHw3JVj_r4E8DMNiB-EoWQ8E6MIoBs_wGBvJvDWhsPFXJm7Mr0YW46gDadnl3Exk-_MA9frZX7F5THUgMTkSkE9obQ2fgNSdum_dvOhqcH5_W5mhUvZ0WszVMi9hBZv8LTUE9s_yH0fxZAmbP2nX4XFS1qk1vKZ5t_xOfnLtINTeEWEMreaacwLuaFBCW3RLmT9oGTA

### Modification d'un member
PUT http://localhost:8000/api/member/3
content-type: application/json

{
    "pseudo" : "moderateur"
}

### Suppression d'un member
DELETE http://localhost:8000/api/member/4

### Ajout d'un member
POST http://localhost:8000/api/member/add
content-type: application/json

{
  "pseudo": "TestApi",
  "password": "abcdefjh",
  "role": "[ROLE_USER]",
  "created_at": "2023-01-01"
}

### Modification d'un member backoffice
PUT http://localhost:8000/back/member/update/3
content-type: application/json

{
    "pseudo" : "moderateur"
}